# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xenvsync < Formula
  desc "Encrypt, commit, and inject .env secrets — no cloud required"
  homepage "https://github.com/nasimstg/xenvsync"
  version "1.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.13.0/xenvsync_1.13.0_darwin_amd64.tar.gz"
      sha256 "546fe1356cd43e92b7cfc695b5b67b4c9964cf9ab92138b1d0c25952efbe6bd0"

      define_method(:install) do
        bin.install "xenvsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.13.0/xenvsync_1.13.0_darwin_arm64.tar.gz"
      sha256 "370ba813a367c2400f03275cee93e8ff457faf4af98c90617441e082e6c65586"

      define_method(:install) do
        bin.install "xenvsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.13.0/xenvsync_1.13.0_linux_amd64.tar.gz"
      sha256 "2b983f9adc875299aada31ffa4c091901dd3c76cbded04f20c952f41d78d0b91"
      define_method(:install) do
        bin.install "xenvsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.13.0/xenvsync_1.13.0_linux_arm64.tar.gz"
      sha256 "83fc999bd1421ba4b1295b0b747ce5845d6470874ea82b3decefdf6ddf148709"
      define_method(:install) do
        bin.install "xenvsync"
      end
    end
  end

  test do
    system "#{bin}/xenvsync", "version"
  end
end
