# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xenvsync < Formula
  desc "Encrypt, commit, and inject .env secrets — no cloud required"
  homepage "https://github.com/nasimstg/xenvsync"
  version "1.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.12.0/xenvsync_1.12.0_darwin_amd64.tar.gz"
      sha256 "cbe9f77c906182530858cc307d58c63d7802b42dddcb24dce8faa33f61f1f870"

      define_method(:install) do
        bin.install "xenvsync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.12.0/xenvsync_1.12.0_darwin_arm64.tar.gz"
      sha256 "9d48a52ce1439d0f7b61bc19ec4a1efab0fd8f2406fd152180ad8527b5fa50dd"

      define_method(:install) do
        bin.install "xenvsync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.12.0/xenvsync_1.12.0_linux_amd64.tar.gz"
      sha256 "d9a124250980eda85dca27f2fe265c6696a68f94842bd79e1568b7efc915b8e3"
      define_method(:install) do
        bin.install "xenvsync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nasimstg/xenvsync/releases/download/v1.12.0/xenvsync_1.12.0_linux_arm64.tar.gz"
      sha256 "d593e4583e074173af20dc44569c47dab11029fe4fdfa469ac30549990cf58da"
      define_method(:install) do
        bin.install "xenvsync"
      end
    end
  end

  test do
    system "#{bin}/xenvsync", "version"
  end
end
